[package]
name = "tls_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = "0.20.2"
webpki = "0.22.0"
webpki-roots = "0.22.1"
